
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "BUPT-CyberSecurity21-HZH", email = "n@ova.moe"},
]
dependencies = []
requires-python = ">=3.10"
license = {text = "MIT"}

[tool.pdm.scripts]
start = 'python main.py'
