class SMTPConnectionError(BaseException):
    ...

class SMTPInvalidCredentialError(BaseException):
    ...

class SMTPInvalidMailError(BaseException):
    ...

class SMTPMailNotExistsError(BaseException):
    ...